### ISSUE TITLE
直接使用git clone的代码放到linux系统无法执行

### ISSUE THREAD

**Issue by aitlp** [moonstack/moon-kibana#3]
存在很多问题：
1.脚本权限问题bin/kibana；
2.大概源代码是在windows上编译的，放到Linux系统中会提示-bash: ./kibana: /bin/sh^M: bad interpreter: No such file or directory
3.解决上面两个问题后还有这个问题：Error: Cannot find module 'commander'

**Comment by longbinma** [comment]
遇到同样的问题，求解答
